/**
 * Stub module for @workspace/api-client-react
 *
 * This module was originally generated by the Replit monorepo workspace.
 * It provides placeholder hooks and types for standalone development.
 * Replace with actual API client implementation (see Issue #13).
 */

import { useMutation, useQuery, type UseMutationResult, type UseQueryResult } from "@tanstack/react-query";

// ── Types ──

export const TicketStatus = {
  OPEN: "open",
  IN_PROGRESS: "in_progress",
  RESOLVED: "resolved",
  CLOSED: "closed",
} as const;

export type TicketStatus = (typeof TicketStatus)[keyof typeof TicketStatus];

export const TicketPriority = {
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high",
  URGENT: "urgent",
} as const;

export type TicketPriority = (typeof TicketPriority)[keyof typeof TicketPriority];

export const TicketCategory = {
  TECHNICAL: "technical",
  BILLING: "billing",
  GENERAL: "general",
  FEATURE_REQUEST: "feature_request",
  BUG_REPORT: "bug_report",
} as const;

export type TicketCategory = (typeof TicketCategory)[keyof typeof TicketCategory];

export interface Ticket {
  id: number;
  ticketNumber: string;
  subject: string;
  description: string;
  status: TicketStatus;
  priority: TicketPriority;
  category: string;
  submitterName: string;
  submitterEmail: string;
  createdAt: string;
  updatedAt: string;
  comments?: Comment[];
}

export interface Comment {
  id: number;
  text: string;
  createdAt: string;
  author: string;
}

export interface TicketStats {
  total: number;
  open: number;
  inProgress: number;
  resolved: number;
  closed: number;
  byPriority: Record<string, number>;
  byCategory: Record<string, number>;
}

// ── Query Keys ──

export const getListTicketsQueryKey = () => ["tickets"];
export const getGetTicketStatsQueryKey = () => ["ticket-stats"];
export const getGetTicketQueryKey = (id: number) => ["ticket", id];

// ── Stub Hooks (localStorage-backed) ──

const STORAGE_KEY = "hd:tickets:v1";

function getStoredTickets(): Ticket[] {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]");
  } catch {
    return [];
  }
}

function saveTickets(tickets: Ticket[]) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(tickets));
}

export function useListTickets(): UseQueryResult<Ticket[]> {
  return useQuery({
    queryKey: getListTicketsQueryKey(),
    queryFn: () => Promise.resolve(getStoredTickets()),
  });
}

export function useGetTicket(id: number): UseQueryResult<Ticket> {
  return useQuery({
    queryKey: getGetTicketQueryKey(id),
    queryFn: () => {
      const ticket = getStoredTickets().find((t) => t.id === id);
      if (!ticket) throw new Error("Ticket not found");
      return Promise.resolve(ticket);
    },
  });
}

export function useGetTicketStats(): UseQueryResult<TicketStats> {
  return useQuery({
    queryKey: getGetTicketStatsQueryKey(),
    queryFn: () => {
      const tickets = getStoredTickets();
      return Promise.resolve({
        total: tickets.length,
        open: tickets.filter((t) => t.status === "open").length,
        inProgress: tickets.filter((t) => t.status === "in_progress").length,
        resolved: tickets.filter((t) => t.status === "resolved").length,
        closed: tickets.filter((t) => t.status === "closed").length,
        byPriority: {},
        byCategory: {},
      });
    },
  });
}

export function useCreateTicket(options?: Record<string, unknown>) {
  return useMutation({
    mutationFn: (data: Partial<Ticket>) => {
      const tickets = getStoredTickets();
      const newTicket: Ticket = {
        id: Date.now(),
        ticketNumber: `HD-${String(tickets.length + 1).padStart(4, "0")}`,
        subject: "",
        description: "",
        status: "open",
        priority: "medium",
        category: "general",
        submitterName: "",
        submitterEmail: "",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        ...data,
      } as Ticket;
      saveTickets([...tickets, newTicket]);
      return Promise.resolve(newTicket);
    },
    ...(options || {}),
  });
}

export function useUpdateTicket(options?: Record<string, unknown>) {
  return useMutation({
    mutationFn: (update: { id: number } & Partial<Ticket>) => {
      const tickets = getStoredTickets();
      const idx = tickets.findIndex((t) => t.id === update.id);
      if (idx === -1) throw new Error("Ticket not found");
      tickets[idx] = { ...tickets[idx], ...update, updatedAt: new Date().toISOString() };
      saveTickets(tickets);
      return Promise.resolve(tickets[idx]);
    },
    ...(options || {}),
  });
}

export function useAddComment(options?: Record<string, unknown>) {
  return useMutation({
    mutationFn: ({ ticketId, text }: { ticketId: number; text: string }) => {
      const tickets = getStoredTickets();
      const ticket = tickets.find((t) => t.id === ticketId);
      if (!ticket) throw new Error("Ticket not found");
      const comment: Comment = { id: Date.now(), text, createdAt: new Date().toISOString(), author: "User" };
      ticket.comments = [...(ticket.comments || []), comment];
      saveTickets(tickets);
      return Promise.resolve(comment);
    },
    ...(options || {}),
  });
}

export function useAiSuggestResponse(options?: Record<string, unknown>) {
  return useMutation({
    mutationFn: ({ ticketId }: { ticketId: number }) => {
      return Promise.resolve({ suggestion: `Auto-generated response for ticket ${ticketId}` });
    },
    ...(options || {}),
  });
}
