/**
 * Type stubs for @workspace/api-client-react
 * 
 * This module was originally generated by a Replit monorepo workspace.
 * These stubs allow TypeScript to compile in standalone mode.
 * Replace with actual API client when backend is implemented (see Issue #13).
 */
declare module "@workspace/api-client-react" {
  import { UseMutationResult, UseQueryResult } from "@tanstack/react-query";

  export enum TicketStatus {
    OPEN = "Open",
    IN_PROGRESS = "In Progress",
    RESOLVED = "Resolved",
    CLOSED = "Closed",
  }

  export enum TicketPriority {
    LOW = "Low",
    MEDIUM = "Medium",
    HIGH = "High",
    CRITICAL = "Critical",
  }

  export enum TicketCategory {
    TECHNICAL = "Technical",
    BILLING = "Billing",
    GENERAL = "General",
    FEATURE_REQUEST = "Feature Request",
    BUG_REPORT = "Bug Report",
  }

  export interface Ticket {
    id: number;
    title: string;
    description: string;
    status: TicketStatus;
    priority: TicketPriority;
    category: TicketCategory;
    createdAt: string;
    updatedAt: string;
    comments?: Comment[];
  }

  export interface Comment {
    id: number;
    text: string;
    createdAt: string;
    author: string;
  }

  export interface TicketStats {
    total: number;
    open: number;
    inProgress: number;
    resolved: number;
    closed: number;
    byPriority: Record<string, number>;
    byCategory: Record<string, number>;
  }

  export function useCreateTicket(): UseMutationResult<Ticket, Error, Partial<Ticket>>;
  export function useUpdateTicket(): UseMutationResult<Ticket, Error, { id: number } & Partial<Ticket>>;
  export function useAddComment(): UseMutationResult<Comment, Error, { ticketId: number; text: string }>;
  export function useAiSuggestResponse(): UseMutationResult<{ suggestion: string }, Error, { ticketId: number }>;
  export function useListTickets(params?: Record<string, unknown>): UseQueryResult<Ticket[]>;
  export function useGetTicket(id: number): UseQueryResult<Ticket>;
  export function useGetTicketStats(): UseQueryResult<TicketStats>;

  export function getListTicketsQueryKey(): string[];
  export function getGetTicketStatsQueryKey(): string[];
  export function getGetTicketQueryKey(id: number): string[];
}
